name: Build and Package C-interattivo

on:
  push:
    branches:
      - main  # Trigger when pushing to the `main` branch
  pull_request:
    branches:
      - main  # Trigger for pull requests to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Arch Linux using Docker
      - name: Set up Arch Linux in Docker
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
            pacman -Syu --noconfirm && \
            pacman -S --noconfirm base-devel git && \
            makepkg -si --noconfirm"

      # Upload the package to GitHub Releases
      - name: Upload package to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.pkg.tar.zst  # Adjust based on your output package format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

