name: Build and Package C-interattivo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Arch Linux in Docker
      - name: Set up Arch Linux in Docker
        run: |
          docker pull archlinux:latest  # Explicitly pull the Arch Linux image
          docker run --rm -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
            # Listing contents of /workspace to confirm PKGBUILD exists
            echo 'Listing contents of /workspace:'
            ls -R /workspace && \
            echo 'Building package...' && \
            pacman -Syu --noconfirm && \
            pacman -S --noconfirm base-devel git && \
            # Create a non-root user and set correct permissions
            useradd -m builder && \
            mkdir -p /workspace/build && \
            chown builder:builder /workspace && \
            chown -R builder:builder /workspace/src && \
            cd /workspace && \
            # Run makepkg as the non-root user
            su builder -c 'makepkg -si --noconfirm'
          "

      # Upload the package to GitHub Releases
      - name: Upload package to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

