name: Build Package

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build package in Docker
      - name: Build package in Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/pkg" archlinux:base-devel bash -c "
            useradd -m builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            pacman -Syu --noconfirm git base-devel &&
            echo 'PACKAGER=\"Builder <builder@example.com>\"' >> /etc/makepkg.conf &&
            echo 'GPGKEY=' >> /etc/makepkg.conf &&
            sed -i 's/^SIGNPKG.*/SIGNPKG=no/' /etc/makepkg.conf &&
            chown -R builder:builder /pkg &&
            su builder -c 'cd /pkg && makepkg --noconfirm --skipinteg --nosign'
          "

      # Step 3: Upload built package as an artifact
      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ./*.pkg.tar.zst

      # Step 4: Fix Git permissions
      - name: Fix Git permissions
        run: |
          sudo chown -R $USER:$USER .git

      # Step 5: Set Git user info
      - name: Set Git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global core.sshCommand "ssh -o StrictHostKeyChecking=no"
          
          # Ensure the repository is fully configured
          git fetch --all

      # Step 6: Create GitHub release tag
      - name: Create GitHub release tag
        run: |
          git tag -a "v1.0.${{ github.run_number }}" -m "Release v1.0.${{ github.run_number }}"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jacklapinza/C-interattivo.git "v1.0.${{ github.run_number }}"

      # Step 7: Create GitHub release and upload package
      - name: Create GitHub release and upload package
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

