name: Build Arch Package

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package in Arch container
        run: |
          docker run --rm \
            -v "$PWD:/pkg" \
            -w /pkg \
            archlinux:base bash -c "
              set -e
              pacman -Syu --noconfirm &&
              pacman -S --noconfirm archlinux-keyring &&
              pacman-key --init &&
              pacman-key --populate archlinux &&
              pacman -S --noconfirm base-devel git &&
              useradd -m builder &&
              chown -R builder:builder /pkg &&
              su builder -c 'cd /pkg && makepkg -s --noconfirm'
            "

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ./*.pkg.tar.zst

