name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package in Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/pkg" archlinux:base-devel bash -c "
            useradd -m builder &&
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
            pacman -Syu --noconfirm git base-devel &&
            echo 'PACKAGER=\"Builder <builder@example.com>\"' >> /etc/makepkg.conf &&
            echo 'GPGKEY=' >> /etc/makepkg.conf &&
            sed -i 's/^SIGNPKG.*/SIGNPKG=no/' /etc/makepkg.conf &&
            chown -R builder:builder /pkg &&
            su builder -c 'cd /pkg && makepkg --noconfirm --skipinteg --nosign'
          "

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: ./*.pkg.tar.zst

