name: Release

on:
  push:
    tags:
      - "*"  # trigger on all tag pushes

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

