name: Release

on:
  push:
    tags:
      - "*"  # trigger on all tag pushes

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./c-interattivo-*.pkg.tar.zst  # match the built file name pattern
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

